package com.balaji.items;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * An item class that represents any physical entity in the grocery store
 * Every item has a item code and parent item code .
 * <p>
 * 'Lays chips' -> item code "1" ,  parent code "ABC"
 * 'XYZ Brand chips' -> item code "2" , parent code "ABC"
 * Parent code for both of them is "ABC" as both of them fall under chips category
 */
public class Item {

    private String itemCode;
    private float price;
    private String name;
    private String parentItemCode;
    private UUID uniqueId;  //Refers to the unique id for each item that is
    // autogenerated when an item is created

    @JsonCreator
    public Item(@JsonProperty("itemCode") String itemCode,
                @JsonProperty("price") float price,
                @JsonProperty("name") String name,
                @JsonProperty("parentItemCode") String parentItemCode) {
        this.itemCode = itemCode;
        this.price = price;
        this.name = name;
        this.parentItemCode = parentItemCode;
        this.uniqueId = UUID.randomUUID();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Item item = (Item) o;
        return Objects.equals(uniqueId, item.uniqueId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uniqueId);
    }

    @Override
    public String toString() {
        return "Item{" +
                "itemCode='" + itemCode + '\'' +
                ", price=" + price +
                ", name='" + name + '\'' +
                ", parentItemCode='" + parentItemCode + '\'' +
                '}';
    }

    public String getItemCode() {
        return itemCode;
    }

    public float getPrice() {
        return price;
    }

    public String getName() {
        return name;
    }

    public String getParentItemCode() {
        return parentItemCode;
    }

    public UUID getUniqueId() {
        return uniqueId;
    }
}
